# Generated by Django 6.0 on 2025-12-09 08:17

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.URLField(null=True, validators=[pages.models.validate_url]),
        ),
    ]
