# Generated by Django 6.0 on 2025-12-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_organization_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_size',
            field=models.CharField(choices=[('Less than 50', '<50'), ('50 - 100', '50-100'), ('100-500', '100-500'), ('500-1K', '500-1K'), ('1K+', '1K+'), ('10K+', '10K+')]),
        ),
    ]
