# Generated by Django 6.0 on 2025-12-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_specialization_alter_organization_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='headquarters',
            field=models.CharField(default='State, Country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_size',
            field=models.CharField(),
        ),
    ]
