# Generated by Django 6.0 on 2025-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_alter_experience_employee'),
        ('pages', '0005_alter_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='experience.skill'),
        ),
    ]
