# Generated by Django 6.0 on 2025-12-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ctc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.SmallIntegerField(default=1),
        ),
    ]
