# Generated by Django 5.2.7 on 2025-11-03 09:55

import django.db.models.deletion
import month.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Bachelor of Engineering', 'Bachelor of Engineering'), ('Master of Engineering', 'Master of Engineering'), ('Bachelor of Computer Applications', 'Bachelor of Computer Applications'), ('Master of Computer Applications', 'Master of Computer Applications'), ('Secondary Education', 'Secondary Education')], max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('starting_time', month.models.MonthField()),
                ('ending_time', month.models.MonthField()),
                ('CGPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Achievements', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Backend Engineer', 'Backend Engineer'), ('Frontend Engineer', 'Frontend Engineer'), ('Fullstack Engineer', 'Fullstack Engineer'), ('Devops', 'Devops'), ('System Administrator', 'System Administrator'), ('Cloud Engineer', 'Cloud Engineer'), ('Python Developer', 'Python Developer'), ('Node.js Developer', 'Node.js Developer'), ('React.js Developer', 'React.js Developer'), ('Django Developer', 'Django Developer'), ('AI Engineer', 'AI Engineer'), ('Technical Support Engineer', 'Technical Support Engineer')], max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField()),
                ('location', models.CharField(choices=[('bengaluru', 'Bengaluru'), ('hyderabad', 'Hyderabad'), ('chennai', 'Chennai'), ('delhi', 'Delhi'), ('gurugram', 'Gurugram'), ('mumbai', 'Mumbai'), ('visakapatnam', 'Visakapatnam'), ('pune', 'Pune'), ('kolkata', 'Kolkata'), ('noida', 'Noida'), ('indore', 'Indore'), ('kochi', 'Kochi'), ('gandhinagar', 'Gandhinagar'), ('surat', 'Surat')], max_length=50)),
                ('location_type', models.CharField(choices=[('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=10)),
                ('Description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(to='experience.skill')),
            ],
        ),
    ]
