# Generated by Django 5.2.7 on 2025-11-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='education',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('Soft Skills', 'Soft Skills'), ('Technical Skills', 'Technical Skills')]),
        ),
        migrations.AlterField(
            model_name='education',
            name='ending_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='starting_time',
            field=models.DateField(),
        ),
    ]
